@echo off
setlocal enabledelayedexpansion

:: ============================================================
::  Neology Average Speed - Full Build Script
::  Generates version, runs PyInstaller, then Inno Setup
:: ============================================================

:: --- Configuration ---
set APP_NAME=NeologyAverageSpeed
set INNO_COMPILER="C:\Program Files (x86)\Inno Setup 6\ISCC.exe"
set SPEC_FILE=neology_average_speed.spec
set ISS_FILE=neology_average_speed_installer.iss
set DIST_DIR=dist
set BUILD_DIR=build

:: ============================================================
echo.
echo ============================================================
echo  %APP_NAME% Build
echo ============================================================
echo.

:: --- Step 1: Generate version stamp ---
echo [1/4] Generating version stamp...
for /f "tokens=1-5 delims=/:. " %%a in ("%date% %time%") do (
    set DD=%%a
    set MM=%%b
    set YYYY=%%c
    set HH=%%d
    set MIN=%%e
)
:: Handle single-digit hour from %time% (leading space)
set HH=%HH: =0%

set BUILD_VERSION=%YYYY%%MM%%DD%.%HH%%MIN%
set BUILD_DATE=%DD%/%MM%/%YYYY% %HH%:%MIN%

echo """Auto-generated by build.bat — do not edit.""" > version.py
echo BUILD_VERSION = "%BUILD_VERSION%" >> version.py
echo BUILD_DATE    = "%BUILD_DATE%" >> version.py

echo     Version : %BUILD_VERSION%
echo     Date    : %BUILD_DATE%
echo.

:: --- Step 2: Clean previous build output ---
echo [2/4] Cleaning previous build output...
if exist "%DIST_DIR%\%APP_NAME%" (
    rmdir /s /q "%DIST_DIR%\%APP_NAME%"
    echo     Removed %DIST_DIR%\%APP_NAME%
)
if exist "%BUILD_DIR%" (
    rmdir /s /q "%BUILD_DIR%"
    echo     Removed %BUILD_DIR%\
)
echo.

:: --- Step 3: PyInstaller ---
echo [3/4] Running PyInstaller...
echo.
pyinstaller %SPEC_FILE% --noconfirm
if errorlevel 1 (
    echo.
    echo ERROR: PyInstaller failed. Aborting build.
    pause
    exit /b 1
)
echo.
echo     PyInstaller completed successfully.
echo.

:: --- Step 4: Inno Setup ---
echo [4/4] Running Inno Setup...
echo.

if not exist %INNO_COMPILER% (
    echo ERROR: Inno Setup compiler not found at %INNO_COMPILER%
    echo        Please install Inno Setup 6 or update the INNO_COMPILER path at the top of this script.
    pause
    exit /b 1
)

%INNO_COMPILER% %ISS_FILE%
if errorlevel 1 (
    echo.
    echo ERROR: Inno Setup failed. Aborting build.
    pause
    exit /b 1
)

:: --- Done ---
echo.
echo ============================================================
echo  BUILD COMPLETE
echo  Version  : %BUILD_VERSION%
echo  Installer: installer_output\%APP_NAME%_Setup_%BUILD_VERSION%.exe
echo ============================================================
echo.
pause